// lib/services/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhmaNkMXs8ZKNOYmhjjfB01U-4hVeh28',
    appId: '1:241690806355:web:b804ca502a9290368d5ea6',
    messagingSenderId: '241690806355',
    projectId: 'speedmaths-pro',
    authDomain: 'speedmaths-pro.firebaseapp.com',
    storageBucket: 'speedmaths-pro.firebasestorage.app',
    measurementId: 'G-HT9J4KBX44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9WysWn82TqrdZPqCVbpNeCAFdH21mfo',
    appId: '1:241690806355:android:679011bd7aada1f58d5ea6',
    messagingSenderId: '241690806355',
    projectId: 'speedmaths-pro',
    storageBucket: 'speedmaths-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfJOds1ruzVtbPkdPirhWqiSxHIsfZJ8',
    appId: '1:241690806355:ios:c5bd0fae1cd2fe2e8d5ea6',
    messagingSenderId: '241690806355',
    projectId: 'speedmaths-pro',
    storageBucket: 'speedmaths-pro.firebasestorage.app',
    iosBundleId: 'com.example.speedmathArena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfJOds1ruzVtbPkdPirhWqiSxHIsfZJ8',
    appId: '1:241690806355:ios:c5bd0fae1cd2fe2e8d5ea6',
    messagingSenderId: '241690806355',
    projectId: 'speedmaths-pro',
    storageBucket: 'speedmaths-pro.firebasestorage.app',
    iosBundleId: 'com.example.speedmathArena',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhhmaNkMXs8ZKNOYmhjjfB01U-4hVeh28',
    appId: '1:241690806355:web:67b25137e4a2b5e18d5ea6',
    messagingSenderId: '241690806355',
    projectId: 'speedmaths-pro',
    authDomain: 'speedmaths-pro.firebaseapp.com',
    storageBucket: 'speedmaths-pro.firebasestorage.app',
    measurementId: 'G-JLQ75FHDLC',
  );
}
